/**
 * Map semantic level to index of spells array
 */
export enum SpellLevel {
  LEVEL1 = 0,
  LEVEL2 = 1,
  LEVEL3 = 2,
  LEVEL4 = 3,
  LEVEL5 = 4,
  LEVEL6 = 5,
}

/**
 * Arcane spells grouped by level 1 - 6
 */
export const spellsArcane = [
  [
    "Arcane Armor pro",
    "Auditory Illusion ill",
    "Beguile Humanoid enc",
    "Blinding Flash bst, elm(fire)",
    "Chameleon trn",
    "Choking Grip dth",
    "Conjure Cacodemon Spawn sum",
    "Counterspell pro",
    "Desiccate bst, elm(water)",
    "Discern Gist det",
    "Discern Magic det",
    "Earth’s Excrescence bst, elm(earth)",
    "Faithful Companion nec",
    "Fan of Flames bst, elm(fire)",
    "Frighten Humanoid enc",
    "Ice Floe elm(water), wal",
    "Illumination* eso",
    "Illusory Figment ill",
    "Infuriate Humanoid enc",
    "Kindle Flame bst, elm(fire)",
    "Leaping trn",
    "Mage Missile bst, elm(any)",
    "Seal Portal eso, mov",
    "Sharpness trn",
    "Shatter Blade bst, elm(earth)",
    "Silent Step trn",
    "Slicing Blow dth",
    "Slickness elm(water), wal",
    "Sling Stone bst, elm(earth)",
    "Slumber enc",
    "Spider Climbing trn",
    "Summon Manes sum",
    "Thunderclap elm(air), bst",
    "Unliving Puppet nec",
    "Wall of Smoke elm(air), wal",
    "Weave Smoke elm(air), wal",
  ],
  [
    "Adjust Self trn",
    "Battering Ram bst, elm(earth)",
    "Bewitch Humanoid enc",
    "Bloody Flux dth",
    "Burning Sparks bst, elm(fire)",
    "Circling Winds elm(air), wal",
    "Conjure Imp sum",
    "Conjure Petty Elemental elm(any), sum",
    "Dark Whisper dth",
    "Deathless Minion nec",
    "Discern Invisible det",
    "Dominate Humanoid enc",
    "Earth’s Wave bst, elm(earth)",
    "Energy Protection elm(any), pro",
    "Frostbite bst, dth, elm(water)",
    "Gale of Wind bst, elm(air)",
    "Halt Humanoidsenc",
    "Hypnotic Sigil enc",
    "Illusory Duplicates ill",
    "Illusory Interior ill",
    "Levitation mov",
    "Locate Object det",
    "Magic Lock mov",
    "Necromantic Potence nec",
    "Ogre Strength trn",
    "Phantasmal Figment ill",
    "Physical Protection pro",
    "Rain of Vitriol bst, elm(water)",
    "Shrouding Fog elm(air), eso, wal",
    "Sudden Staircase wal",
    "Summon Insect Swarm sum",
    "Sunflare bst, elm(fire)",
    "Swimming elm(water), trn",
    "Vitriolic Infusion elm(water), trn",
    "Warp Wood bst, elm(earth)",
    "Webbing eso, wal",
  ],
  [
    "Avian Messenger sum, trn",
    "Bewitch Crowd enc",
    "Boil Blood bst, elm(fire)",
    "Chimerical Figment ill",
    "Clairaudiency det",
    "Clairvoyancy det",
    "Cone of Frost bst, elm(water)",
    "Conjure Hellion sum",
    "Create Chasm elm(earth), wal",
    "Deflect Ordinary Missiles pro",
    "Dismember dth",
    "Dispel Magic pro",
    "Dominate Monster enc",
    "Earth’s Teeth bst, elm(earth)",
    "Fireball bst, elm(fire)",
    "Flight mov",
    "Force of Impetus elm(earth), mov",
    "Growth* trn",
    "Ice Sheet elm(water), wal",
    "Illumination, Perpetual eso",
    "Inaudibility ill",
    "Incite Madness enc",
    "Infuriate Crowd enc",
    "Invisibility ill",
    "Lightless Vision trn",
    "Lightning Strike bst, elm(air), eso",
    "Rune of Warding eso, pro",
    "Skinchange trn",
    "Speak with Dead nec",
    "Spellward pro",
    "Strengthen the Unliving nec",
    "Summon Hellhounds sum",
    "Thunderbolt bst, elm(air)",
    "Wall of Thunder elm(air), wal",
    "Water Breathing elm(water), trn",
    "Weave Fire elm(fire), wal",
  ],
  [
    "Animate Undead",
    "Arcane Shift mov",
    "Bewitch Monster enc",
    "Cloud of Poison elm(air), wal",
    "Conjure Incubus sum",
    "Conjure Major Elemental elm(any), sum",
    "Earth’s Tremor bst, elm(earth)",
    "Energy Invulnerability elm(any), pro",
    "Cone of Fear enc",
    "Flesh to Ash dth",
    "Giant Strength trn",
    "Growth, Plant* trn",
    "Guise Self trn",
    "Halt Monsters enc",
    "Hidden Host ill",
    "Illusory Terrain ill",
    "Indiscernibility eso, pro",
    "Inferno bst, elm(fire)",
    "Iron Maiden dth",
    "Locate Treasure det",
    "Magic Carpet mov",
    "Physical Invulnerability pro",
    "Safe Travels trn",
    "Scouring Zephyr bst, elm(air)",
    "Scry det, eso",
    "Shrieking Skull eso, nec",
    "Slumber, Deep enc",
    "Spectral Figment ill",
    "Spellward Other pro",
    "Sphere of Invulnerability, Lesser pro",
    "Summon Shadow sum",
    "Sunder Structure bst, elm(earth)",
    "Telepathy det, eso",
    "Wall of Flame elm(fire), wal",
    "Wall of Frost elm(water), wal",
    "Weave Water elm(water), wal",
  ],
  [
    "Blast Ward",
    "Capsizing Wave bst, elm(water)",
    "Carnage dth",
    "Circle of Agony dth",
    "Cone of Paralysis enc",
    "Conjure Dybbuk sum",
    "Conjure Supreme Elemental elm(any), sum",
    "Contact Other Sphere det, eso",
    "Control Winds elm (air), eso",
    "Curse of the Swine trn",
    "Deflect Ordinary Weapons pro",
    "Dominate Plants enc",
    "Earth’s Mire* elm(earth), trn",
    "Fillet and Serve dth, nec",
    "Firestorm bst, elm(fire)",
    "Flay the Slain nec",
    "Forest Enchantment enc",
    "Forgetfulness enc",
    "Guise Other trn",
    "Ice Storm bst, elm(water)",
    "Lay of the Land det",
    "Life Transfer dth",
    "Lightless Vision, Mass trn",
    "Locate Haunting det",
    "Mirage ill",
    "Phantasmal Horror ill",
    "Rouse the Fallen nec",
    "Selective Fire bst, elm(fire)",
    "Soul Swap nec",
    "Spectral Legion ill",
    "Summon Ooze sum",
    "Summon Weather elm(air), eso",
    "Telekinesis mov",
    "Teleportation mov",
    "Wall of Stone elm(earth), wal",
    "X-Ray Vision det, eso",
  ],
  [
    "Anti-Magic Sphere pro",
    "Banner of Invincibility pro",
    "Body Swap nec, trn",
    "Clairaudiency, Greater det",
    "Clairvoyancy, Greater det",
    "Conflagration bst, elm(fire)",
    "Conjure Fiend sum",
    "Conjure Genie elm(any), sum",
    "Control Weather elm(air), eso",
    "Disfigure Body and Soul dth",
    "Disintegration dth",
    "Earth’s Movement elm(earth), eso, mov",
    "Enslave Humanoid enc",
    "Level Water elm(water), eso, mov",
    "Locate Distant Object det",
    "Locate Place of Power det",
    "Madness of Crowds enc",
    "Necromantic Invulnerability nec",
    "Panic enc",
    "Passageway eso",
    "Perpetual Figment ill",
    "Petrification* dth",
    "Programmatic Figment ill",
    "Quest enc, eso",
    "Reveal Ritual Magic det",
    "Soul Eating dth, nec",
    "Spellwarded Zone pro",
    "Sphere of Invulnerability, Grt. pro",
    "Summon Invisible Stalker sum",
    "Torpor nec",
    "Transform Other trn",
    "Transform Self trn",
    "Trollblood trn",
    "Wall of Annihilation wal",
    "Wall of Corpses nec, wal",
    "Wall of Force wal",
  ],
];

/**
 * Divine spells grouped by level 1 - 6
 */
export const spellsDivine = [
  [
    "Allure enc",
    "Angelic Choir ill",
    "Bane-Rune trn",
    "Call of the Wolf sum",
    "Counterspell pro",
    "Cure Light Injury* hea",
    "Delay Disease hea",
    "Destroy Dead dth",
    "Discern Evil* det",
    "Discern Gist det",
    "Discern Magic det",
    "Discern Poison det",
    "Faithful Companion nec",
    "Frighten Beast enc",
    "Holy Circle* pro",
    "Illumination* eso",
    "Infuriate Beast enc",
    "Kindle Flame bst, elm(fire)",
    "Locate Animal or Plant det",
    "Pass Without Trace trn",
    "Predict Weather det",
    "Purify Food and Water* eso",
    "Remove Fear* eso, hea",
    "Salving Rest eso, hea",
    "Sanctuary eso, pro",
    "Seal Portal eso, mov",
    "Shatter Blade bst, elm(earth)",
    "Sling Stone bst, elm(earth)",
    "Unliving Puppet nec",
    "Word of Command enc",
  ],
  [
    "Augury det, eso",
    "Beguile Humanoid enc",
    "Bewitch Beast enc",
    "Call of the Wolf Pack sum",
    "Choking Grip dth",
    "Circling Winds elm(air), wal",
    "Cure Moderate Injury* hea",
    "Dark Whisper dth",
    "Deathless Minion nec",
    "Delay Poison hea",
    "Discern Bewitchment* det",
    "Divine Armor pro",
    "Divine Grace pro",
    "Dominate Beasts enc",
    "Energy Protection elm(any)",
    "Halt Humanoids enc",
    "Holy Blessing* eso, pro",
    "Holy Chant eso, pro",
    "Magic Lock mov",
    "Necromantic Potence nec",
    "Noiselessness ill",
    "Physical Protection pro",
    "Righteous Wrath trn",
    "Shimmer pro",
    "Slicing Blow dth",
    "Slumber enc",
    "Speak with Beasts det",
    "Spiritual Weapon bst, eso",
    "Swift Sword mov",
    "Transform Beast trn",
  ],
  [
    "Avian Messenger sum, trn",
    "Bewitch Humanoid enc",
    "Call of the Wild Bear sum",
    "Clairaudiency det",
    "Clairvoyancy det",
    "Cure Blindness* hea",
    "Cure Disease* hea",
    "Cure Major Injury* hea",
    "Deflect Ordinary Missiles pro",
    "Discern Curse* det",
    "Discern Invisible det",
    "Dispel Magic pro",
    "Divine Protection pro",
    "Growth, Beast trn",
    "Holy Circle, Sustained* pro",
    "Holy Prayer mov",
    "Illumination, Perpetual* eso",
    "Invulnerability to Evil* pro",
    "Lightning Strike bst, elm(air), eso",
    "Phantasmal Figment ill",
    "Remove Curse* hea",
    "Rune of Warding eso",
    "Speak with Dead nec",
    "Spellward pro",
    "Strengthen the Unliving nec",
    "Striking trn",
    "Swift Sword, Sustained mov",
    "Water Breathing elm(water), trn",
    "Water Walking elm(water), mov",
    "Winged Flight trn",
  ],
  [
    "Angelic Aura",
    "Call of the Galloping Herd sum",
    "Call of the Regal Pride sum",
    "Crafting trn",
    "Create Water elm(water), eso",
    "Cure Serious Injury* hea",
    "Death Ward pro",
    "Dismember dth",
    "Divination det",
    "Energy Invulnerability elm(any), pro",
    "Gale of Wind elm(air), bst",
    "Growth trn",
    "Inaudibility ill",
    "Indiscernibility eso, pro",
    "Inspire Awe* enc",
    "Invisibility ill",
    "Lightless Vision trn",
    "Neutralize Poison* hea",
    "Physical Invulnerability pro",
    "Protection from Temperature pro",
    "Repair Disfigurement & Dis.* hea",
    "Skinchange trn",
    "Smite Undead* nec",
    "Snakes to Staffs* trn",
    "Speak with Plants det, eso",
    "Spellward Other pro",
    "Sphere of Invulnerability, Lesser pro",
    "Spirit of Healing* hea",
    "Sunflare bst, elm(fire)",
    "Tongues det, eso",
  ],
  [
    "Atonement",
    "Blast Ward pro",
    "Boil Blood bst, elm(fire)",
    "Call of the Great Cats sum",
    "Communion det, eso",
    "Cone of Fear enc",
    "Control Winds elm(air), eso",
    "Create Food eso",
    "Cure Critical Injury* hea",
    "Curse of the Swine trn",
    "Deflect Ordinary Weapons pro",
    "Dominate Monster enc",
    "Fate det, eso",
    "Fiery Pillar bst, elm(fire)",
    "Giant Strength trn",
    "Growth, Plant trn",
    "Guise Self trn",
    "Healing Circle hea",
    "Lay of the Land det",
    "Locate Haunting det",
    "Restore Life and Limb* hea",
    "Safe Travels trn",
    "Scry det, eso",
    "Spiritwalk trn",
    "Strength of Mind* pro",
    "Summon Insect Plague sum",
    "Sword of Fire elm(fire), eso, trn",
    "True Seeing det, eso",
    "Turn to Dust dth",
    "Vigor trn",
  ],
  [
    "Anti-Magic Sphere pro",
    "Arrows of the Sun elm(fire), trn",
    "Banner of Invincibility pro",
    "Barrier of Blades wal",
    "Bath of the Goddess trn",
    "Bewitch Monster enc",
    "Blast Ward, Greater pro",
    "Call of the Ancient Tusk sum",
    "Call of the Aerophract Steeds sum",
    "Clairaudiency, Greater det",
    "Clairvoyancy, Greater det",
    "Dispel Evil* eso, pro",
    "Fillet and Serve dth",
    "Flesh to Ash dth",
    "Guise Other trn",
    "Hidden Host ill",
    "Home Ward eso, pro",
    "Illusory Terrain ill",
    "Level Water elm(water), eso, mov",
    "Locate Place of Power det",
    "Phoenix Aura bst, elm(fire)",
    "Prophetic Dream det",
    "Quest enc, eso",
    "Salvific Rain bst, elm(water)",
    "Slumber, Deep enc",
    "Spectral Figment ill",
    "Spellward Zone pro",
    "Sphere of Invulnerability, Grtr. pro",
    "Summon Weather eso",
    "Summon Winged Herald sum",
  ],
];
